version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql_pw
      MYSQL_ROOT_PASSWORD: takashi_pass
    ports:
      - 3306:3306
    # volumes:
    #   - ./mysql/data:/var/lib/mysql      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - mysql